name: unsaid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  confetti: ^0.8.0

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  adaptive_icon_background: "#F5F8FF"
  adaptive_icon_foreground: assets/logo.png


